language: go
go: 1.7.3
dist: trusty
sudo: false

env:
  global:
    - secure: "lKecg86M5FH4E2yCZwM96PxESMjeZ0tsIm3xhrlQjvrRZcUPTdgDWNZKHf57m1gjtjpYLrZfqcCIrzDv1CPnZmK/5iBS7+565kdVKlO3aXGSI8FizhfnYjOBtqE5YP0ia9ri89uRebXvqPryxo/EsnMT280hHmPqdU208ElMVheEJNDeCO6SiPVmJY99aF7cniMjIBdQWNs7nGSdxegk+5z23uGHbxGDBZufv5maGzCyJisbdWym19EjF02Ien0e9ahwcBP5j0SDESeKYNAioEjorIsyCTkO0USezRncha6A9l2szn5RR+Xmrqj4i6EacLTqW7Xxtm1LAWZSBMSp1UiWpfNZKglj6UabJvAS5pNhmCWbQJWODEutAmUtQV+xOScmzseX4nn1xL+XIA8Oo47OASFqdVsv7K997TIJ/KBdo4NH0I2tEFdOemPLnaAYKt9/Wp5y6VEuLXi5bEtm5Th1zs5IFT+zKV0FYMHhLFN25jwX3jvUWaCaelwDvd/NkPgYOvQkIEbieLFLpP9Iw59fZRxzBYItg3dJGoSZ4ekpceOdl76WuUrk+XjUZFJ8Up88i0wmdmimMwnmuUydaqgzHuGHscIYPyxgj3NrmJSakCsEuNvPjumjhMHm3yMR49dREzO26/DywyNcMNN4a8ybDbSqTk8qhBmj3fglswo="
    - 'DEPLOY_BRANCH="master"'
    - 'DEPLOY_REPO_SLUG="vim-jp/vimdoc-en"'
    - 'DEPLOY_USER_NAME="vimdoc-en on travis-ci"'
    - 'DEPLOY_USER_EMAIL="vimdoc-en+travis-ci@vim-jp.org"'

script:
  - sh ./tools/install_sshkey_github.sh "$CI_KEY" ./tools/ci@vimdoc-en.vim-jp.org.enc ~/.ssh/ci@vimdoc-en.vim-jp.org
  - '[ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-gh-pages.sh _gh-pages'
