language: go
go: 1.7.3
dist: trusty
sudo: false

env:
  global:
    - secure: "rDF/aXaZ6HJL5f7zcxr5qT/SK6/IUXjIAVt2XrEJ7msXVzJCW0qlrQH044fIxHD2bY4bmINiyAy0otUekVPI/seebNvgRKpJoCAI7XF5kUSXgqgtC7iAZ5z8aLNDzqtjdi0bWowm0nc65DzXERdZNACPPLTvfM9ThExCKvyNUgxuEpg+PgjD3sNxcYpGrNJ9hsjIYmW+PxbcHs5ZaReVp+6F5+lnwYbkUl1UgtPHr08ianzHwDkytO/5Em0pkpKm0Z3Akee/6cb+5lLHXCrYt7qauYgfBKanyQ9cbGut13nXmkIZi38z9HPk3FXyAAmhfjEvyXNNpT5IloIa6LPy2M5/TIlleSjPdZoDLFO4ZCkKXwhH896hcvjhCGTZEB50cJBhndXnPx4svoyrGHjDWrV07ndejkPkOU5z9aW1xi2YZfKfsMKz3hHWH5PKMBQvLqkmREWfPCezjjq8A30WUcPT0OIqfsIODAAdtOz4vc8W3okpl+tRiJ7se1xdSh822u8UlR4Px+r/MaIsT4mfCTHImUORaVRzfHLfCKrVE4n7CJG+Qy7kfM6VNM8yV5LWJChGCi9uR14ZgnYAhsO4u2AT0P0o/8QC//V/62acXzUItOeNvgBM2svHhkQ70uOt14cdR+u9H429T3/fxDsk0jMi/PaQAJMuXVwE7UuJtgg="
    - 'DEPLOY_BRANCH="master"'
    - 'DEPLOY_REPO_SLUG="vim-jp/vimdoc-en"'
    - 'DEPLOY_USER_NAME="vimdoc-en on travis-ci"'
    - 'DEPLOY_USER_EMAIL="vimdoc-en+travis-ci@vim-jp.org"'

script:
  - sh ./tools/install_sshkey_github.sh "$CI_KEY" ./tools/ci@vimdoc-en.vim-jp.org.enc ~/.ssh/ci@vimdoc-en.vim-jp.org
  - '[ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-gh-pages.sh _gh-pages'
