language: go
go: 1.7.3
dist: trusty
sudo: false

env:
  global:
    - 'DEPLOY_BRANCH="master"'
    - 'DEPLOY_REPO_SLUG="vim-jp/vimdoc-en"'
    - 'DEPLOY_USER_NAME="vimdoc-en on travis-ci"'
    - 'DEPLOY_USER_EMAIL="vimdoc-en+travis-ci@vim-jp.org"'

script:
  - sh ./tools/install_sshkey_github.sh $encrypted_3ac247a44cc5_key $encrypted_3ac247a44cc5_iv ./tools/ci@vimdoc-en.vim-jp.org.enc ~/.ssh/ci@vimdoc-en.vim-jp.org
  - |
    if [ "$TRAVIS_BRANCH" = "$DEPLOY_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      sh ./tools/deploy-gh-pages.sh _gh-pages
    fi
